# Generated by Django 5.0.13 on 2025-12-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('num_licencia', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('tipo_sangre', models.CharField(max_length=10)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('disponibilidad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('tratamiento_recomendado', models.TextField()),
                ('nivel_gravedad', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Hospital.citamedica')),
            ],
        ),
        migrations.AddField(
            model_name='citamedica',
            name='id_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Hospital.doctor'),
        ),
        migrations.CreateModel(
            name='FacturaHospital',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Hospital.citamedica')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Hospital.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='citamedica',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Hospital.paciente'),
        ),
    ]
