# Generated by Django 5.0.13 on 2025-12-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='capacidad_critica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='codigo_sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='equipamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='estado_mantenimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='fecha_ultima_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo_uso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='disponibilidad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
