# Generated by Django 5.0.13 on 2025-12-04 17:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Hospital', '0002_sala_capacidad_critica_sala_codigo_sala_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citamedica',
            options={'ordering': ['-fecha_cita', '-hora_cita'], 'verbose_name': 'Cita Médica', 'verbose_name_plural': 'Citas Médicas'},
        ),
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Diagnóstico', 'verbose_name_plural': 'Diagnósticos'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='facturahospital',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Factura Hospital', 'verbose_name_plural': 'Facturas Hospital'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AddField(
            model_name='citamedica',
            name='costo_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='duracion_minutos',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='lugar_cita',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='medio_reserva',
            field=models.CharField(blank=True, choices=[('WEB', 'Web'), ('TEL', 'Teléfono'), ('PER', 'Personalmente'), ('APP', 'App Móvil')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MED', 'Media'), ('ALTA', 'Alta'), ('URG', 'Urgente')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='tipo_atencion',
            field=models.CharField(blank=True, choices=[('PRE', 'Presencial'), ('VIR', 'Virtual'), ('DOM', 'Domicilio')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='tipo_cita',
            field=models.CharField(blank=True, choices=[('CONS', 'Consulta'), ('CONT', 'Control'), ('EMER', 'Emergencia'), ('SEGU', 'Seguimiento'), ('TERA', 'Terapia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='codigo_cie10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='codigo_diagnostico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='especialista_encargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='estado_diagnostico',
            field=models.CharField(blank=True, choices=[('PREL', 'Preliminar'), ('CONF', 'Confirmado'), ('DESC', 'Descartado'), ('REVI', 'En Revisión')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='resultado_examen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='seguimiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='tipo_diagnostico',
            field=models.CharField(blank=True, choices=[('CLIN', 'Clínico'), ('LAB', 'Laboratorio'), ('IMG', 'Imagenología'), ('PAT', 'Patológico'), ('COM', 'Combinado')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certificaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='direccion_clinica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='estado_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experiencia_anios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='horario_trabajo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='idiomas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facturahospital',
            name='codigo_autorizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturahospital',
            name='comentarios_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturahospital',
            name='descripcion_servicios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturahospital',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='facturahospital',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facturahospital',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturahospital',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facturahospital',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('CONS', 'Consulta'), ('LAB', 'Laboratorio'), ('IMG', 'Imágenes'), ('HOS', 'Hospitalización'), ('FARM', 'Farmacia'), ('TER', 'Terapia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo/a'), ('U', 'Unión libre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_seguro_social',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('DNI', 'Documento Nacional de Identidad'), ('PAS', 'Pasaporte'), ('CE', 'Carnet de Extranjería'), ('LIC', 'Licencia de Conducir'), ('OTRO', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('CONF', 'Confirmada'), ('CANC', 'Cancelada'), ('REAL', 'Realizada'), ('AUS', 'Ausente')], default='PEND', max_length=50),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='hora_cita',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='id_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app_Hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app_Hospital.paciente'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='id_cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='app_Hospital.citamedica'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='nivel_gravedad',
            field=models.CharField(blank=True, choices=[('LEV', 'Leve'), ('MOD', 'Moderado'), ('GRA', 'Grave'), ('CRI', 'Crítico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='tratamiento_recomendado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='num_licencia',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facturahospital',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='facturahospital',
            name='estado_pago',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('PAG', 'Pagado'), ('PAR', 'Parcial'), ('CANC', 'Cancelado'), ('ANU', 'Anulado')], default='PEND', max_length=50),
        ),
        migrations.AlterField(
            model_name='facturahospital',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facturahospital',
            name='id_cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='app_Hospital.citamedica'),
        ),
        migrations.AlterField(
            model_name='facturahospital',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='app_Hospital.paciente'),
        ),
        migrations.AlterField(
            model_name='facturahospital',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('CHE', 'Cheque'), ('TRA', 'Transferencia'), ('SEG', 'Seguro'), ('OTRO', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facturahospital',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='codigo_sala',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='estado_mantenimiento',
            field=models.CharField(blank=True, choices=[('OPT', 'Óptimo'), ('REG', 'Regular'), ('MANT', 'En Mantenimiento'), ('REP', 'En Reparación'), ('INH', 'Inhabilitada')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CONS', 'Consulta'), ('QUIR', 'Quirófano'), ('URG', 'Urgencias'), ('HOS', 'Hospitalización'), ('LAB', 'Laboratorio'), ('ADM', 'Administrativa'), ('OTRO', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo_uso',
            field=models.CharField(blank=True, choices=[('GEN', 'General'), ('ESP', 'Especializada'), ('CRI', 'Cuidados Críticos'), ('DIAG', 'Diagnóstico'), ('TRAT', 'Tratamiento')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together={('id_doctor', 'fecha_cita', 'hora_cita')},
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['fecha_cita', 'estado'], name='app_Hospita_fecha_c_d7856c_idx'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['id_paciente', 'id_doctor'], name='app_Hospita_id_paci_4ea8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostico',
            index=models.Index(fields=['codigo_cie10'], name='app_Hospita_codigo__074d77_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostico',
            index=models.Index(fields=['nivel_gravedad'], name='app_Hospita_nivel_g_f452ab_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['especialidad'], name='app_Hospita_especia_fa95e4_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['estado_activo'], name='app_Hospita_estado__6eb257_idx'),
        ),
        migrations.AddIndex(
            model_name='facturahospital',
            index=models.Index(fields=['estado_pago'], name='app_Hospita_estado__e92e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='facturahospital',
            index=models.Index(fields=['numero_factura'], name='app_Hospita_numero__8c932e_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellido', 'nombre'], name='app_Hospita_apellid_da9c43_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['numero_identificacion'], name='app_Hospita_numero__fc29a1_idx'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['tipo', 'disponibilidad'], name='app_Hospita_tipo_e4384c_idx'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['codigo_sala'], name='app_Hospita_codigo__834db6_idx'),
        ),
    ]
