# Generated by Django 5.0.13 on 2025-12-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Hospital', '0003_alter_citamedica_options_alter_diagnostico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='id_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas', to='app_Hospital.paciente'),
        ),
    ]
